### ISSUE TITLE
Builds with the snappy feature fail on macOS Catalina

### ISSUE THREAD

**Issue by ghost** [skade/leveldb-sys#11]
When I try to build the `master` branch with `snappy` feature, the build fails:

```
$ cargo build --features=snappy -vvv
   Compiling leveldb-sys v2.0.3 (/private/tmp/leveldb-sys)
   Compiling libc v0.2.19
     Running `DYLD_FALLBACK_LIBRARY_PATH='/private/tmp/leveldb-sys/target/debug/deps:/Users/alex/.rustup/toolchains/stable-x86_64-apple-darwin/lib:/Users/alex/.rustup/toolchains/stable-x86_64-apple-darwin/lib:/Users/alex/lib:/usr/local/lib:/usr/lib' CARGO_PKG_VERSION_MINOR=0 CARGO_PKG_VERSION_PATCH=3 CARGO_PKG_VERSION=2.0.3 CARGO_PKG_VERSION_PRE= CARGO_PKG_DESCRIPTION='FFI bindings to LevelDB' CARGO_PKG_VERSION_MAJOR=2 CARGO_MANIFEST_DIR=/private/tmp/leveldb-sys CARGO_PKG_NAME=leveldb-sys CARGO_PKG_HOMEPAGE= CARGO_PKG_REPOSITORY='https://github.com/skade/leveldb-sys' CARGO_PKG_AUTHORS='Andrew Dunham <andrew@du.nham.ca>:Florian Gilcher <florian.gilcher@asquera.de>' CARGO=/Users/alex/.rustup/toolchains/stable-x86_64-apple-darwin/bin/cargo rustc --crate-name build_script_build src/build.rs --color always --crate-type bin --emit=dep-info,link -C debuginfo=2 --cfg 'feature="snappy"' -C metadata=22e1228ec02acd1c -C extra-filename=-22e1228ec02acd1c --out-dir /private/tmp/leveldb-sys/target/debug/build/leveldb-sys-22e1228ec02acd1c -C incremental=/private/tmp/leveldb-sys/target/debug/incremental -L dependency=/private/tmp/leveldb-sys/target/debug/deps`
     Running `DYLD_FALLBACK_LIBRARY_PATH='/private/tmp/leveldb-sys/target/debug/deps:/Users/alex/.rustup/toolchains/stable-x86_64-apple-darwin/lib:/Users/alex/.rustup/toolchains/stable-x86_64-apple-darwin/lib:/Users/alex/lib:/usr/local/lib:/usr/lib' CARGO_PKG_VERSION_MINOR=2 CARGO_PKG_VERSION_PATCH=19 CARGO_PKG_VERSION=0.2.19 CARGO_PKG_VERSION_PRE= CARGO_PKG_DESCRIPTION='A library for types and bindings to native C functions often found in libc or
other common platform libraries.
' CARGO_PKG_VERSION_MAJOR=0 CARGO_MANIFEST_DIR=/Users/alex/.cargo/registry/src/github.com-1ecc6299db9ec823/libc-0.2.19 CARGO_PKG_NAME=libc CARGO_PKG_HOMEPAGE='https://github.com/rust-lang/libc' CARGO_PKG_REPOSITORY='https://github.com/rust-lang/libc' CARGO_PKG_AUTHORS='The Rust Project Developers' CARGO=/Users/alex/.rustup/toolchains/stable-x86_64-apple-darwin/bin/cargo rustc --crate-name libc /Users/alex/.cargo/registry/src/github.com-1ecc6299db9ec823/libc-0.2.19/src/lib.rs --error-format=json --json=diagnostic-rendered-ansi,artifacts --crate-type lib --emit=dep-info,metadata,link -C debuginfo=2 --cfg 'feature="default"' --cfg 'feature="use_std"' -C metadata=57e2c4f985d8e2e3 -C extra-filename=-57e2c4f985d8e2e3 --out-dir /private/tmp/leveldb-sys/target/debug/deps -L dependency=/private/tmp/leveldb-sys/target/debug/deps --cap-lints warn`
     Running `/private/tmp/leveldb-sys/target/debug/build/leveldb-sys-22e1228ec02acd1c/build-script-build`
[leveldb-sys 2.0.3] [build] Started
[leveldb-sys 2.0.3] [snappy] Cleaning
[leveldb-sys 2.0.3] make: *** No rule to make target `distclean'.  Stop.
[leveldb-sys 2.0.3] [snappy] Configuring
[leveldb-sys 2.0.3] thread 'main' panicked at 'configure failed', src/libcore/option.rs:1166:5
[leveldb-sys 2.0.3] note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace.
[leveldb-sys 2.0.3] checking for a BSD-compatible install... /usr/local/bin/ginstall -c
[leveldb-sys 2.0.3] checking whether build environment is sane... yes
[leveldb-sys 2.0.3] checking for a thread-safe mkdir -p... /usr/local/bin/gmkdir -p
[leveldb-sys 2.0.3] checking for gawk... no
[leveldb-sys 2.0.3] checking for mawk... no
[leveldb-sys 2.0.3] checking for nawk... no
[leveldb-sys 2.0.3] checking for awk... awk
[leveldb-sys 2.0.3] checking whether make sets $(MAKE)... yes
[leveldb-sys 2.0.3] checking build system type... x86_64-apple-darwin19.0.0
[leveldb-sys 2.0.3] checking host system type... x86_64-apple-darwin19.0.0
[leveldb-sys 2.0.3] checking how to print strings... printf
[leveldb-sys 2.0.3] checking for style of include used by make... GNU
[leveldb-sys 2.0.3] checking for gcc... gcc
[leveldb-sys 2.0.3] checking whether the C compiler works... yes
[leveldb-sys 2.0.3] checking for C compiler default output file name... a.out
[leveldb-sys 2.0.3] checking for suffix of executables...
[leveldb-sys 2.0.3] checking whether we are cross compiling... no
[leveldb-sys 2.0.3] checking for suffix of object files... o
[leveldb-sys 2.0.3] checking whether we are using the GNU C compiler... yes
[leveldb-sys 2.0.3] checking whether gcc accepts -g... yes
[leveldb-sys 2.0.3] checking for gcc option to accept ISO C89... none needed
[leveldb-sys 2.0.3] checking dependency style of gcc... gcc3
[leveldb-sys 2.0.3] checking for a sed that does not truncate output... /usr/local/bin/gsed
[leveldb-sys 2.0.3] checking for grep that handles long lines and -e... /usr/bin/grep
[leveldb-sys 2.0.3] checking for egrep... /usr/bin/grep -E
[leveldb-sys 2.0.3] checking for fgrep... /usr/bin/grep -F
[leveldb-sys 2.0.3] checking for ld used by gcc... /Library/Developer/CommandLineTools/usr/bin/ld
[leveldb-sys 2.0.3] checking if the linker (/Library/Developer/CommandLineTools/usr/bin/ld) is GNU ld... no
[leveldb-sys 2.0.3] checking for BSD- or MS-compatible name lister (nm)... /usr/bin/nm -B
[leveldb-sys 2.0.3] checking the name lister (/usr/bin/nm -B) interface... BSD nm
[leveldb-sys 2.0.3] checking whether ln -s works... yes
[leveldb-sys 2.0.3] checking the maximum length of command line arguments... 196608
[leveldb-sys 2.0.3] checking whether the shell understands some XSI constructs... yes
[leveldb-sys 2.0.3] checking whether the shell understands "+="... yes
[leveldb-sys 2.0.3] checking how to convert x86_64-apple-darwin19.0.0 file names to x86_64-apple-darwin19.0.0 format... func_convert_file_noop
[leveldb-sys 2.0.3] checking how to convert x86_64-apple-darwin19.0.0 file names to toolchain format... func_convert_file_noop
[leveldb-sys 2.0.3] checking for /Library/Developer/CommandLineTools/usr/bin/ld option to reload object files... -r
[leveldb-sys 2.0.3] checking for objdump... objdump
[leveldb-sys 2.0.3] checking how to recognize dependent libraries... pass_all
[leveldb-sys 2.0.3] checking for dlltool... no
[leveldb-sys 2.0.3] checking how to associate runtime and link libraries... printf %s\n
[leveldb-sys 2.0.3] checking for ar... ar
[leveldb-sys 2.0.3] checking for archiver @FILE support... no
[leveldb-sys 2.0.3] checking for strip... strip
[leveldb-sys 2.0.3] checking for ranlib... ranlib
[leveldb-sys 2.0.3] checking command to parse /usr/bin/nm -B output from gcc object... ok
[leveldb-sys 2.0.3] checking for sysroot... no
[leveldb-sys 2.0.3] checking for mt... no
[leveldb-sys 2.0.3] checking if : is a manifest tool... no
[leveldb-sys 2.0.3] checking for dsymutil... dsymutil
[leveldb-sys 2.0.3] checking for nmedit... nmedit
[leveldb-sys 2.0.3] checking for lipo... lipo
[leveldb-sys 2.0.3] checking for otool... otool
[leveldb-sys 2.0.3] checking for otool64... no
[leveldb-sys 2.0.3] checking for -single_module linker flag... yes
[leveldb-sys 2.0.3] checking for -exported_symbols_list linker flag... yes
[leveldb-sys 2.0.3] checking for -force_load linker flag... yes
[leveldb-sys 2.0.3] checking how to run the C preprocessor... gcc -E
[leveldb-sys 2.0.3] checking for ANSI C header files... yes
[leveldb-sys 2.0.3] checking for sys/types.h... yes
[leveldb-sys 2.0.3] checking for sys/stat.h... yes
[leveldb-sys 2.0.3] checking for stdlib.h... yes
[leveldb-sys 2.0.3] checking for string.h... yes
[leveldb-sys 2.0.3] checking for memory.h... yes
[leveldb-sys 2.0.3] checking for strings.h... yes
[leveldb-sys 2.0.3] checking for inttypes.h... yes
[leveldb-sys 2.0.3] checking for stdint.h... yes
[leveldb-sys 2.0.3] checking for unistd.h... yes
[leveldb-sys 2.0.3] checking for dlfcn.h... yes
[leveldb-sys 2.0.3] checking for objdir... .libs
[leveldb-sys 2.0.3] checking if gcc supports -fno-rtti -fno-exceptions... yes
[leveldb-sys 2.0.3] checking for gcc option to produce PIC... -fno-common -DPIC
[leveldb-sys 2.0.3] checking if gcc PIC flag -fno-common -DPIC works... yes
[leveldb-sys 2.0.3] checking if gcc static flag -static works... no
[leveldb-sys 2.0.3] checking if gcc supports -c -o file.o... yes
[leveldb-sys 2.0.3] checking if gcc supports -c -o file.o... (cached) yes
[leveldb-sys 2.0.3] checking whether the gcc linker (/Library/Developer/CommandLineTools/usr/bin/ld) supports shared libraries... yes
[leveldb-sys 2.0.3] checking dynamic linker characteristics... darwin19.0.0 dyld
[leveldb-sys 2.0.3] checking how to hardcode library paths into programs... immediate
[leveldb-sys 2.0.3] checking whether stripping libraries is possible... yes
[leveldb-sys 2.0.3] checking if libtool supports shared libraries... yes
[leveldb-sys 2.0.3] checking whether to build shared libraries... no
[leveldb-sys 2.0.3] checking whether to build static libraries... yes
[leveldb-sys 2.0.3] checking for g++... g++
[leveldb-sys 2.0.3] checking whether we are using the GNU C++ compiler... yes
[leveldb-sys 2.0.3] checking whether g++ accepts -g... yes
[leveldb-sys 2.0.3] checking dependency style of g++... gcc3
[leveldb-sys 2.0.3] checking how to run the C++ preprocessor... g++ -E
[leveldb-sys 2.0.3] checking for ld used by g++... /Library/Developer/CommandLineTools/usr/bin/ld
[leveldb-sys 2.0.3] checking if the linker (/Library/Developer/CommandLineTools/usr/bin/ld) is GNU ld... no
[leveldb-sys 2.0.3] checking whether the g++ linker (/Library/Developer/CommandLineTools/usr/bin/ld) supports shared libraries... yes
[leveldb-sys 2.0.3] checking for g++ option to produce PIC... -fno-common -DPIC
[leveldb-sys 2.0.3] checking if g++ PIC flag -fno-common -DPIC works... yes
[leveldb-sys 2.0.3] checking if g++ static flag -static works... no
[leveldb-sys 2.0.3] checking if g++ supports -c -o file.o... yes
[leveldb-sys 2.0.3] checking if g++ supports -c -o file.o... (cached) yes
[leveldb-sys 2.0.3] checking whether the g++ linker (/Library/Developer/CommandLineTools/usr/bin/ld) supports shared libraries... yes
[leveldb-sys 2.0.3] checking dynamic linker characteristics... darwin19.0.0 dyld
[leveldb-sys 2.0.3] checking how to hardcode library paths into programs... immediate
[leveldb-sys 2.0.3] checking whether byte ordering is bigendian... no
[leveldb-sys 2.0.3] checking for size_t... yes
[leveldb-sys 2.0.3] checking for ssize_t... yes
[leveldb-sys 2.0.3] checking for stdint.h... (cached) yes
[leveldb-sys 2.0.3] checking stddef.h usability... yes
[leveldb-sys 2.0.3] checking stddef.h presence... yes
[leveldb-sys 2.0.3] checking for stddef.h... yes
[leveldb-sys 2.0.3] checking sys/mman.h usability... yes
[leveldb-sys 2.0.3] checking sys/mman.h presence... yes
[leveldb-sys 2.0.3] checking for sys/mman.h... yes
[leveldb-sys 2.0.3] checking sys/resource.h usability... yes
[leveldb-sys 2.0.3] checking sys/resource.h presence... yes
[leveldb-sys 2.0.3] checking for sys/resource.h... yes
[leveldb-sys 2.0.3] checking windows.h usability... no
[leveldb-sys 2.0.3] checking windows.h presence... no
[leveldb-sys 2.0.3] checking for windows.h... no
[leveldb-sys 2.0.3] checking byteswap.h usability... no
[leveldb-sys 2.0.3] checking byteswap.h presence... no
[leveldb-sys 2.0.3] checking for byteswap.h... no
[leveldb-sys 2.0.3] checking sys/byteswap.h usability... no
[leveldb-sys 2.0.3] checking sys/byteswap.h presence... no
[leveldb-sys 2.0.3] checking for sys/byteswap.h... no
[leveldb-sys 2.0.3] checking sys/endian.h usability... no
[leveldb-sys 2.0.3] checking sys/endian.h presence... no
[leveldb-sys 2.0.3] checking for sys/endian.h... no
[leveldb-sys 2.0.3] checking sys/time.h usability... yes
[leveldb-sys 2.0.3] checking sys/time.h presence... yes
[leveldb-sys 2.0.3] checking for sys/time.h... yes
[leveldb-sys 2.0.3] checking for mmap... yes
[leveldb-sys 2.0.3] checking for 'gtest-config'... checking for gtest-config... no
[leveldb-sys 2.0.3] no
[leveldb-sys 2.0.3] checking for pkg-config... /usr/local/bin/pkg-config
[leveldb-sys 2.0.3] checking pkg-config is at least version 0.9.0... yes
[leveldb-sys 2.0.3] checking for gflags... no
[leveldb-sys 2.0.3] checking if the compiler supports __builtin_expect... yes
[leveldb-sys 2.0.3] checking if the compiler supports __builtin_ctzll... yes
[leveldb-sys 2.0.3] checking for zlibVersion in -lz... yes
[leveldb-sys 2.0.3] checking for lzo1x_1_15_compress in -llzo2... yes
[leveldb-sys 2.0.3] checking for lzf_compress in -llzf... no
[leveldb-sys 2.0.3] checking for fastlz_compress in -lfastlz... no
[leveldb-sys 2.0.3] checking for qlz_compress in -lquicklz... no
[leveldb-sys 2.0.3] configure: creating ./config.status
[leveldb-sys 2.0.3] config.status: creating Makefile
[leveldb-sys 2.0.3] config.status: creating snappy-stubs-public.h
[leveldb-sys 2.0.3] config.status: creating config.h
[leveldb-sys 2.0.3] config.status: executing depfiles commands
[leveldb-sys 2.0.3] config.status: executing libtool commands
error: failed to run custom build command for `leveldb-sys v2.0.3 (/private/tmp/leveldb-sys)`

Caused by:
  process didn't exit successfully: `/private/tmp/leveldb-sys/target/debug/build/leveldb-sys-22e1228ec02acd1c/build-script-build` (exit code: 101)
--- stdout
[build] Started
[snappy] Cleaning
[snappy] Configuring
checking for a BSD-compatible install... /usr/local/bin/ginstall -c
checking whether build environment is sane... yes
checking for a thread-safe mkdir -p... /usr/local/bin/gmkdir -p
checking for gawk... no
checking for mawk... no
checking for nawk... no
checking for awk... awk
checking whether make sets $(MAKE)... yes
checking build system type... x86_64-apple-darwin19.0.0
checking host system type... x86_64-apple-darwin19.0.0
checking how to print strings... printf
checking for style of include used by make... GNU
checking for gcc... gcc
checking whether the C compiler works... yes
checking for C compiler default output file name... a.out
checking for suffix of executables...
checking whether we are cross compiling... no
checking for suffix of object files... o
checking whether we are using the GNU C compiler... yes
checking whether gcc accepts -g... yes
checking for gcc option to accept ISO C89... none needed
checking dependency style of gcc... gcc3
checking for a sed that does not truncate output... /usr/local/bin/gsed
checking for grep that handles long lines and -e... /usr/bin/grep
checking for egrep... /usr/bin/grep -E
checking for fgrep... /usr/bin/grep -F
checking for ld used by gcc... /Library/Developer/CommandLineTools/usr/bin/ld
checking if the linker (/Library/Developer/CommandLineTools/usr/bin/ld) is GNU ld... no
checking for BSD- or MS-compatible name lister (nm)... /usr/bin/nm -B
checking the name lister (/usr/bin/nm -B) interface... BSD nm
checking whether ln -s works... yes
checking the maximum length of command line arguments... 196608
checking whether the shell understands some XSI constructs... yes
checking whether the shell understands "+="... yes
checking how to convert x86_64-apple-darwin19.0.0 file names to x86_64-apple-darwin19.0.0 format... func_convert_file_noop
checking how to convert x86_64-apple-darwin19.0.0 file names to toolchain format... func_convert_file_noop
checking for /Library/Developer/CommandLineTools/usr/bin/ld option to reload object files... -r
checking for objdump... objdump
checking how to recognize dependent libraries... pass_all
checking for dlltool... no
checking how to associate runtime and link libraries... printf %s\n
checking for ar... ar
checking for archiver @FILE support... no
checking for strip... strip
checking for ranlib... ranlib
checking command to parse /usr/bin/nm -B output from gcc object... ok
checking for sysroot... no
checking for mt... no
checking if : is a manifest tool... no
checking for dsymutil... dsymutil
checking for nmedit... nmedit
checking for lipo... lipo
checking for otool... otool
checking for otool64... no
checking for -single_module linker flag... yes
checking for -exported_symbols_list linker flag... yes
checking for -force_load linker flag... yes
checking how to run the C preprocessor... gcc -E
checking for ANSI C header files... yes
checking for sys/types.h... yes
checking for sys/stat.h... yes
checking for stdlib.h... yes
checking for string.h... yes
checking for memory.h... yes
checking for strings.h... yes
checking for inttypes.h... yes
checking for stdint.h... yes
checking for unistd.h... yes
checking for dlfcn.h... yes
checking for objdir... .libs
checking if gcc supports -fno-rtti -fno-exceptions... yes
checking for gcc option to produce PIC... -fno-common -DPIC
checking if gcc PIC flag -fno-common -DPIC works... yes
checking if gcc static flag -static works... no
checking if gcc supports -c -o file.o... yes
checking if gcc supports -c -o file.o... (cached) yes
checking whether the gcc linker (/Library/Developer/CommandLineTools/usr/bin/ld) supports shared libraries... yes
checking dynamic linker characteristics... darwin19.0.0 dyld
checking how to hardcode library paths into programs... immediate
checking whether stripping libraries is possible... yes
checking if libtool supports shared libraries... yes
checking whether to build shared libraries... no
checking whether to build static libraries... yes
checking for g++... g++
checking whether we are using the GNU C++ compiler... yes
checking whether g++ accepts -g... yes
checking dependency style of g++... gcc3
checking how to run the C++ preprocessor... g++ -E
checking for ld used by g++... /Library/Developer/CommandLineTools/usr/bin/ld
checking if the linker (/Library/Developer/CommandLineTools/usr/bin/ld) is GNU ld... no
checking whether the g++ linker (/Library/Developer/CommandLineTools/usr/bin/ld) supports shared libraries... yes
checking for g++ option to produce PIC... -fno-common -DPIC
checking if g++ PIC flag -fno-common -DPIC works... yes
checking if g++ static flag -static works... no
checking if g++ supports -c -o file.o... yes
checking if g++ supports -c -o file.o... (cached) yes
checking whether the g++ linker (/Library/Developer/CommandLineTools/usr/bin/ld) supports shared libraries... yes
checking dynamic linker characteristics... darwin19.0.0 dyld
checking how to hardcode library paths into programs... immediate
checking whether byte ordering is bigendian... no
checking for size_t... yes
checking for ssize_t... yes
checking for stdint.h... (cached) yes
checking stddef.h usability... yes
checking stddef.h presence... yes
checking for stddef.h... yes
checking sys/mman.h usability... yes
checking sys/mman.h presence... yes
checking for sys/mman.h... yes
checking sys/resource.h usability... yes
checking sys/resource.h presence... yes
checking for sys/resource.h... yes
checking windows.h usability... no
checking windows.h presence... no
checking for windows.h... no
checking byteswap.h usability... no
checking byteswap.h presence... no
checking for byteswap.h... no
checking sys/byteswap.h usability... no
checking sys/byteswap.h presence... no
checking for sys/byteswap.h... no
checking sys/endian.h usability... no
checking sys/endian.h presence... no
checking for sys/endian.h... no
checking sys/time.h usability... yes
checking sys/time.h presence... yes
checking for sys/time.h... yes
checking for mmap... yes
checking for 'gtest-config'... checking for gtest-config... no
no
checking for pkg-config... /usr/local/bin/pkg-config
checking pkg-config is at least version 0.9.0... yes
checking for gflags... no
checking if the compiler supports __builtin_expect... yes
checking if the compiler supports __builtin_ctzll... yes
checking for zlibVersion in -lz... yes
checking for lzo1x_1_15_compress in -llzo2... yes
checking for lzf_compress in -llzf... no
checking for fastlz_compress in -lfastlz... no
checking for qlz_compress in -lquicklz... no
configure: creating ./config.status
config.status: creating Makefile
config.status: creating snappy-stubs-public.h
config.status: creating config.h
config.status: executing depfiles commands
config.status: executing libtool commands

--- stderr
make: *** No rule to make target `distclean'.  Stop.
thread 'main' panicked at 'configure failed', src/libcore/option.rs:1166:5
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace.
```

This small change fixes the error:
```diff
diff --git a/src/build.rs b/src/build.rs
index 2d17d7a..8e6c3ff 100644
--- a/src/build.rs
+++ b/src/build.rs
@@ -28,7 +28,8 @@ fn build_snappy(is_bsd: bool) {
 
     // Configure the build
     println!("[snappy] Configuring");
-    Command::new("./configure").current_dir(&snappy_path)
+    Command::new("/bin/sh").current_dir(&snappy_path)
+                               .arg("./configure")
                                .arg("--disable-shared")
                                .status().ok().expect("configure failed");
```

It might have something to do with the change of the default shell in Catalina.

**Comment by skade** [comment]
Released 2.0.5. https://crates.io/crates/leveldb-sys/2.0.5

Thanks for the patch!
